# Generated by Django 4.2.5 on 2024-01-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_remove_post_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
